### ISSUE TITLE
I beg you to protect your secrets

### ISSUE THREAD

**Issue by tigthor** [lovelysystems/lovely-pgutil#2]
**Hello My Friend that I've not met.**
As we all know the internet is becoming a large place or a large field and and we should start caring for security. And as long s I know the consequences companies or people met when they are breached. That is why i recommend you to either hide or remove this [Exposed PostgreSQL file which contains db passwords](https://github.com/lovelysystems/lovely-pgutil/blob/559ef0f0aa94dd5b14bbb674f8b55a5d45c5e080/localdev/pgpass) . You may see it as a small problem but trust me my friend ,a malicious person getting your private things like passwords. The effect can be devastating. 
Thank You my Friend.

**Comment by dobe** [comment]
this is just for the tests
